config/routes.rb
Rails.application.routes.draw do
  resources :blurbs
  resources :images
  resources :datasources

  root to: 'projects#index'

  resources :projects do
    get :typeahead, :on => :collection
  end
  
  resources :builders do
  end
  

end

app/models/blurb.rb
class Blurb < ActiveRecord::Base
  validates :description, presence: true, length: { minimum: 2, maximum: 2000 }

  ## Ensure we refer to a valid datasource_id
  validates :datasource, presence: true

  ## Ensure we refer to a valid project
  validates :project, presence: true

  validates_associated :images

  validates_with BlurbValidator
  
  scope :for_project, ->(project_id){ where('project_id = ?', project_id) if (project_id) }

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, :reject_if => ->(a) { a[:url].blank? }

  belongs_to :project
  belongs_to :datasource

end

app/controllers/blurbs_controller.rb
class BlurbsController < ApplicationController
  before_action :set_blurb, only: [:show, :edit, :update, :destroy]

  # GET /blurbs
  # GET /blurbs.json
  def index
    @blurbs = Blurb.all
  end

  # GET /blurbs/1
  # GET /blurbs/1.json
  def show
    @images = Image.for_blurb(@blurb.id)
  end

  # GET /blurbs/new
  def new
    @blurb = Blurb.new
    4.times { @blurb.images.build }
  end

  # GET /blurbs/1/edit
  def edit
    (@blurb.images.count...4).each do |c|
      @blurb.images.build
    end
  end

  # POST /blurbs
  # POST /blurbs.json
  def create
    @blurb = Blurb.new(blurb_params)

    respond_to do |format|
      if @blurb.save
        format.html { redirect_to project_url(@blurb.project, :blurb_id => @blurb.id), notice: 'Blurb was successfully created.' }
        format.json { render :show, status: :created, location: @blurb }
      else
        format.html { render :new }
        format.json { render json: @blurb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blurbs/1
  # PATCH/PUT /blurbs/1.json
  def update
    respond_to do |format|
      if @blurb.update(blurb_params)
        format.html { redirect_to project_url(@blurb.project, :blurb_id => @blurb.id), notice: 'Blurb was successfully updated.' }
        format.json { render :show, status: :ok, location: @blurb }
      else
        format.html { render :edit }
        format.json { render json: @blurb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blurbs/1
  # DELETE /blurbs/1.json
  def destroy
    @blurb.destroy
    respond_to do |format|
      format.html { redirect_to project_url(@blurb.project), notice: 'Blurb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blurb
      @blurb = Blurb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blurb_params
      params.require(:blurb).permit(:datasource_id, :description, :project_id, images_attributes: [:id, :url])
    end
end

app/helpers/blurbs_helper.rb
module BlurbsHelper
end

app/views/blurbs/_form.html.erb
<%= form_for(@blurb) do |f| %>
  <% if @blurb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blurb.errors.count, "error") %> prohibited this blurb from being saved:</h2>

      <ul>
      <% @blurb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :project_id %><br>
      <%= f.collection_select(:project_id, Project.all, :id, :title) %>
  </div>

  <div class="field">
      <%= f.label :datasource_id %><br>
      <%= f.collection_select(:datasource_id, Datasource.all, :id, :title) %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, size: "100x10"  %>
  </div>

  <%= f.fields_for :images do |i| %>
    <div class="field">
      <%= i.label :image %>
      <%= i.text_field :url %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blurbs/edit.html.erb
<h1>Editing Blurb</h1>

<%= render 'form' %>

app/views/blurbs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blurbs</h1>

<table class="table table-condensed">
  <thead>
    <tr>
        <th>Project</th>
        <th>Datasource</th>
        <th>Description</th>
        <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blurbs.each do |blurb| %>
      <tr>
        <td><%= link_to blurb.project.title, project_path(blurb.project) %></td>
        <td><%= link_to blurb.datasource.title, datasource_path(blurb.datasource) %></td>
        <td><%= blurb.description %></td>
        <td><%= link_to 'Show', blurb %></td>
        <td><%= link_to 'Edit', edit_blurb_path(blurb) %></td>
        <td><%= link_to 'Destroy', blurb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/blurbs/new.html.erb
<h1>New Blurb</h1>

<%= render 'form' %>

<%= link_to 'Back', blurbs_path %>

app/views/blurbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Datasource:</strong>
  <%= link_to @blurb.datasource.title, datasource_path(@blurb.datasource) %>
</p>

<p>
  <strong>Project:</strong>
  <%= link_to @blurb.project.title, project_path(@blurb.project) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blurb.description %>
</p>

<h3>Images</h3>
<% @images.each do |i| %>
  <p>
    <%= link_to "#{i.url} (#{i.id})", image_path(i) %>
  </p>
<% end %>

<%= link_to 'Edit', edit_blurb_path(@blurb) %> |
<%= link_to 'Back', blurbs_path %>