config/routes.rb
Rails.application.routes.draw do
  resources :blurbs
  resources :images
  resources :datasources

  root to: 'projects#index'

  resources :projects do
    get :typeahead, :on => :collection
  end
  
  resources :builders do
  end
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :title, presence: true, length: { minimum: 2, maximum: 20 }
  validates :latitude, :longitude, presence: true, numericality: { only_integer: false }

  ## This ensures we refer to a valid builder_id
  validates :builder, presence: true

  validates_uniqueness_of :name, :title

  has_many :blurbs, dependent: :destroy

  belongs_to :builder

  scope :search, ->(keyword){ where('title LIKE ?', "%#{keyword.downcase}%") if keyword.present? }

  scope :unverified, ->(unverified) { where(verified: false) if unverified.present? }

  scope :for_builder, ->(builder_id){ where('builder_id = ?', builder_id) if (builder_id) }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project
      .includes(:builder)
      .search(params[:keyword])
      .unverified(params[:unverified])

    ## Redirect to a project if this was a search with only 1 result
    if @projects.count == 1 and params[:keyword].present?
      redirect_to @projects.first, notice: "You were redirected"
    end

    build_map_markers @projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @blurbs = Blurb.for_project(@project.id)
    ## Create an empty Blurb for the 'add blurb' form
    @blurb = Blurb.new(:project => @project)
    3.times {  @blurb.images.build }

    @blurb_panel_id = params[:blurb_id].to_i
  end

  # GET /projects/new
  def new
    @project = Project.new
    build_map_markers Project.all
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    @project.builder = Builder.find_by_name('nestoria') if @project.builder.nil?

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /projects/typeahead.json
  def typeahead
    searchterm = params[:a]
    project_names =  Project.all.collect(&:title).grep(/#{searchterm}/i).map { |title| { value: title } }


    respond_to do |format|
      format.json { render json: project_names }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :title, :verified, :latitude, :longitude, :builder_id)
    end

    def build_map_markers(projects)
      @map_markers = Gmaps4rails.build_markers(projects) do | project, marker |
        marker.lat project.latitude
        marker.lng project.longitude
        marker.infowindow project.title
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_blurb.html.erb
        <div id="blurb_<%= b.id %>" class="tab-pane fade in row">
          <div class="row">
            <div class="lead well col-md-9">
              <%= b.description %>
            </div>
            <div class="col-md-3">
              <ul class="list-inline pull-right text-center"> 
                <li><%= button_to "Edit", edit_blurb_path(b), :class => "btn btn-primary", :method => :get %></li>
                <li><%= button_to 'Destroy', blurb_path(b), :class => 'btn btn-danger btn-sm', :method => :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
            </div>
          </div>

          <div class="row">
            <% b.images.each do |i| %>
              <div class="container col-md-3">
                <a href="<%= i.url %>" class="thumbnail">
                  <%= image_tag(i.url, alt: i.url, size: "200x150") %>
                  <figcaption align="center">
                    <%= i.url %>
                    <%= button_to 'Destroy', image_path(i), :class => 'btn btn-danger btn-xs', :method => :delete, data: { confirm: 'Are you sure?' } %>
                  </figcaption>              
                </a>
              </div>
            <% end %>
          </div>
        </div>

app/views/projects/_blurb_pane.html.erb
 <div id="blurb_<%= blurb.id %>" class="tab-pane fade in row <%= "active" if blurb.id == @blurb_panel_id %>">
  <div class="row">
    <div class="lead well col-md-9">
      <%= blurb.description %>
    </div>
    <div class="col-md-3">
      <ul class="list-inline pull-right text-center"> 
        <li><%= button_to "Edit", edit_blurb_path(blurb), :class => "btn btn-primary", :method => :get %></li>
        <li><%= button_to 'Destroy', blurb_path(blurb), :class => 'btn btn-danger btn-sm', :method => :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </div>
  </div>

  <div class="row">
    <% blurb.images.each do |i| %>
      <div class="container col-md-3">
        <a href="<%= i.url %>" class="thumbnail">
          <%= image_tag(i.url, alt: i.url) %>
          <figcaption align="center">
            <%= i.url %>
            <%= button_to 'Destroy', image_path(i), :class => 'btn btn-danger btn-xs', :method => :delete, data: { confirm: 'Are you sure?' } %>
          </figcaption>              
        </a>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => "" } do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>

  <div style='width: 800px;'>
    <div id="map" style='width: 800px; height: 400px;'></div>
  </div>

  <form>
    <div class="form-inline">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
      <div class="form-group">
        <%= label_tag 'Lat / Long' %>
        <%= f.text_field :latitude, :class => 'form-control', :readonly => true %>
        <%= f.text_field :longitude, :class => 'form-control', :readonly => true %>
      </div>
    </div>
      <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :class => 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :builder_id %>
        <%= f.collection_select(:builder_id, Builder.all, :id, :title, {}, :class => 'form-control') %>
      </div>
      <div class="form-group">
        <%= f.label :verified %>
        <%= f.check_box :verified %>
      </div>
      <%= f.submit :class => 'btn btn-primary' %>
  </form>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= javascript_tag defer: 'defer' do -%>
  map_markers = [{
  "lat": <%= @project.latitude %>,
  "lng": <%= @project.longitude %>,
  "picture": {
  "url": "http://s.uk.nestoria.nestimg.com/i/realestate/all/all/favicon-32x32.png",
  "width":  32,
  "height": 32
  },
  "infowindow": "<%= @project.title %>"
  }];
  map_add_marker = 1;
<% end -%>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div id="map" style='height: 400px;'></div>
  </div>
</div>

<br>

<div class='row'>
  <div class="col-md-8 col-md-offset-2" id="search_form">
    <form role="search" class="form-inline well">
      <div class="form-group" id="bloodhound">
        <label for="searchField">Search:</label>
        <input type='text' id="searchField" data-remote="<%= typeahead_projects_url(:format => :json)  %>" class='form-control typeahead' value='<%= params[:keyword] %>' name='keyword' placeholder='Project title'>
        <button class="btn btn-default" type="submit" id="search_submit">
          <i class="glyphicon glyphicon-search"></i>
        </button>
      </div>
    </form>
  </div>
</div>

<br>

<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Title</th>
          <th>Verified</th>
          <th>Latitude</th>
          <th>Longitude</th>
          <th>Builder</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td><%= project.name %></td>
            <td><%= link_to project.title, project %></td>
            <td><%= project.verified %></td>
            <td><%= project.latitude %></td>
            <td><%= project.longitude %></td>
            <td>
              <% if project.builder %>
                <%= link_to project.builder.title, builder_path(project.builder) %>
              <% end %>
            </td>
            <td><%= link_to 'Edit', edit_project_path(project) %></td>
            <td><a href="#" data-map-lat="<%= project.latitude %>"
                   data-map-long="<%= project.longitude %>">Zoom to</a></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= javascript_tag defer: 'defer' do -%>
 map_markers = <%=raw @map_markers.to_json %>;
 map_add_marker = 0;
<% end -%>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= javascript_tag defer: 'defer' do -%>
  map_markers = <%=raw @map_markers.to_json %>;
  map_add_marker = 1;
<% end -%>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <div class="row">

    <div class="col-md-5 well">
      <h1><%= @project.title %></h1>
      <ul class="list-unstyled">
        <li><strong>Name:</strong> <%= @project.name %> </li>
        <li><strong>Title:</strong> <%= @project.title %> </li>
        <li><strong>Verified:</strong> <%= @project.verified %> </li>
        <li><strong>Lat / Long:</strong> <%= @project.latitude %>, <%= @project.longitude %> </li>
        <li><strong>Builder:</strong> <%= link_to @project.builder.title, builder_path(@project.builder) %> </li>
        <li><strong>Created at:</strong> <%= @project.created_at %>
        <li><strong>Updated at:</strong> <%= @project.updated_at %>          
      </ul>

    </div>

    <div class="col-md-5">
      <div id="map" style='width: 400px; height: 400px;'></div>
    </div>
    
    <div class="col-md-2" id="edit_buttons">
      <ul class="list-inline pull-right text-center">
        <li><%= button_to "Edit", edit_project_path, :class => "btn btn-primary", :method => :get %></li>
        <li><%= button_to "Destroy", project_path, :class => "btn btn-danger", :method => :delete,
            data: { confirm: 'Are you sure?' } %></li>
      </ul>
      <ul class="list-inline pull-right text-center">      
        <li><%= button_to "Verify", edit_project_path, :class => "btn btn-success", :method => :get %></li>
      </ul>
    </div>
    
  </div>
</div>

<div class="container col-md-10 col-md-offset-1">

  <ul class="nav nav-tabs">
    <% @blurbs.each do |b| %>
      <li class="nav-tab-bar <%= "active" if b.id == @blurb_panel_id %>">
        <a data-toggle="tab" href="#blurb_<%= b.id %>"><%= b.datasource.title %></a>
      </li>
    <% end %>      
    <li class="nav-tab-bar">
      <a data-toggle="tab" href="#blurb_new">Add Blurb</a>
    </li>
  </ul>

  <div class="tab-content">

    <%= render :partial => 'blurb_pane', :collection => @blurbs, :as => :blurb %>

    <div id="blurb_new" class="tab-pane fade in row">
      <%= form_for(@blurb) do |f| %>
        <% if @blurb.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@blurb.errors.count, "error") %> prohibited this blurb from being saved:</h2>
            
            <ul>
              <% @blurb.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        
        <%= f.hidden_field(:project_id) %>
        
        <div class="field">
          <%= f.label :datasource_id %><br>
          <%= f.collection_select(:datasource_id, Datasource.all, :id, :title) %>
        </div>
        
        <div class="field">
          <%= f.label :description %><br>
          <%= f.text_area :description, size: "100x20" %>
        </div>

        <div class="field">
          <%= f.fields_for :image do |builder| %>
            <p>poo</p>
            <p>
              <%= builder.label :id %> - <%= builder.label :url, "URL" %>
            </p>
          <% end %>
        </div>
        
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>
      
      
    </div>
    
    
  </div>
</div>

<%= javascript_tag defer: 'defer' do -%>
  map_markers = [{
  "lat": <%= @project.latitude %>,
  "lng": <%= @project.longitude %>,
  "picture": {
  "url": "http://s.uk.nestoria.nestimg.com/i/realestate/all/all/favicon-32x32.png",
  "width":  32,
  "height": 32
  },
  "infowindow": "<%= @project.title %>"
  }];
  map_add_marker = 0;
<% end -%>