config/routes.rb
Rails.application.routes.draw do
  resources :blurbs
  resources :images
  resources :datasources

  root to: 'projects#index'

  resources :projects do
    get :typeahead, :on => :collection
  end
  
  resources :builders do
  end
  

end

app/views/layouts/_footer.html.erb
<hr>

<footer class="footer">
  <div class="container">
    <p class="text-muted">Projects<sup>2</sup> Test Rig</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Projects<sup>2</sup></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"> <%= link_to 'Home', root_path %></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Country<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li class="dropdown-header">Blurg</li>

                <% countries.each do |country | %>
                  <li><a href="#"><%= country %></a></li>                  
                <% end %>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">New<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Project', new_project_path %></li>
                <li><%= link_to 'Datasource', new_datasource_path %></li>                
                <li><%= link_to 'Builder', new_builder_path %></li>
                <li class="divider"></li>
                <li><%= link_to 'Blurb', new_blurb_path %></li>
                <li><%= link_to 'Image', new_image_path %></li>                
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">List<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Project', projects_path %></li>
                <li><%= link_to 'Datasource', datasources_path %></li>                
                <li><%= link_to 'Builder', builders_path %></li>
                <li class="divider"></li>
                <li><%= link_to 'Blurb', blurbs_path %></li>
                <li><%= link_to 'Image', images_path %></li>                
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Work<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Unverified Projects', projects_path(:unverified => 1) %></li>
              </ul>
            </li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li> <%= link_to 'Metrics', "http://metrics.lokku.net/" %></li>
            <li> <%= link_to 'Ops Dashboard', "http://www:3030" %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/_meta.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projects</title>
  <%= render 'layouts/meta' %>

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700,300,400' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  
  <div class="container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>
</body>
</html>